# docker-compose.yaml
services:
  web:
    build: ./back/
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017
    working_dir: /app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: mongo
    ports:
      - "27017:27017"
